service: dev
runtime: nodejs16

handlers:
  - url: /
    static_files: public/index.html
    upload: public/index.html
    secure: always

  - url: /blog/.*
    static_files: public/blog/index.html
    upload: public/blog/index.html
    secure: always

  - url: /((.*\/)*[^\/]+\.[^\/]+)$
    static_files: public/\1
    upload: public/.*
    secure: always

  - url: /(.*)\/$
    static_files: public/\1/index.html
    upload: public/.*/index.html
    secure: always

  - url: /(.*)$
    static_files: public/\1/index.html
    upload: public/.*/index.html
    secure: always

  - url: /.*
    static_files: public/index.html
    upload: public/index.html
    secure: always

