name: Build & Deploy to App Engine

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      # Setup gcloud CLI
      - name: Login and setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GCR_JSON_KEY }}
          project_id: ${{ secrets.ELLIPSIS_PROJECT_ID }}

      - name: Install packages
        run: |
          yarn install

      - name: Build the app
        run: |
          yarn build

      # deploy to app engine
      - name: Deploy
        run: |
          gcloud app deploy app.yaml
